export const cardList = [
  {
    id: 1,
    topic: 'Web Design',
    color: 'orange',
    title: 'Название задачи',
    date: '30.10.23',
    columnTitle: 'Без статуса',
  },
  {
    id: 2,
    topic: 'Research',
    color: 'green',
    title: 'Название задачи',
    date: '30.10.23',
    columnTitle: 'Без статуса',
  },
  {
    id: 3,
    topic: 'Web Design',
    color: 'orange',
    title: 'Название задачи',
    date: '30.10.23',
    columnTitle: 'Без статуса',
  },
  {
    id: 4,
    topic: 'Copywriting',
    color: 'purple',
    title: 'Название задачи',
    date: '30.10.23',
    columnTitle: 'Без статуса',
  },
  {
    id: 5,
    topic: 'Research',
    color: 'green',
    title: 'Название задачи',
    date: '30.10.23',
    columnTitle: 'Нужно сделать',
  },
  {
    id: 6,
    topic: 'Research',
    color: 'green',
    title: 'Название задачи',
    date: '30.10.23',
    columnTitle: 'В работе',
  },
  {
    id: 7,
    topic: 'Copywriting',
    color: 'purple',
    title: 'Название задачи',
    date: '30.10.23',
    columnTitle: 'В работе',
  },
  {
    id: 8,
    topic: 'Web Design',
    color: 'orange',
    title: 'Название задачи',
    date: '30.10.23',
    columnTitle: 'В работе',
  },
  {
    id: 9,
    topic: 'Research',
    color: 'green',
    title: 'Название задачи',
    date: '30.10.23',
    columnTitle: 'Тестирование',
  },
  {
    id: 10,
    topic: 'Research',
    color: 'green',
    title: 'Название задачи',
    date: '30.10.23',
    columnTitle: 'Готово',
  },
]
